apiVersion: v1
kind: Service
metadata:
  name: app-mysql-inte
  labels:
    app: app-mysql-inte
spec:
  ports:
    - port: 3306
  selector:
    app: app-mysql
    tier: mysql
  type: NodePort
  #clusterIP: 10.103.196.189
