apiVersion: v1
kind: Service
metadata:
  name: app-mysql
  labels:
    app: app-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: app-mysql
    tier: mysql
  #type: NodePort
    #clusterIP: 10.103.196.189
