apiVersion: v1
kind: Service
metadata:
  name: platform-mongo
  labels:
    app: platform-mongo
spec:
  ports:
    - port: 27017
  selector:
    app: platform-mongo
    tier: mongo
#  type: NodePort
#  clusterIP: None
