apiVersion: v1
kind: Service
metadata:
  name: platform-service-timer
  labels:
    app: platform-service-timer
spec:
  ports:
    - port: 8081
  selector:
    app: platform-service-timer
    tier: service-timer
