apiVersion: v1
kind: Service
metadata:
  name: platform-service-file
  labels:
    app: platform-service-file
spec:
  ports:
    - port: 8094
  selector:
    app: platform-service-file
    tier: service-file
