apiVersion: v1
kind: Service
metadata:
  name: platform-mysql
  labels:
    app: platform-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: platform-mysql
    tier: mysql
#  type: NodePort
#clusterIP: None
