apiVersion: v1
kind: Service
metadata:
  name: platform-redis
  labels:
    app: platform-redis
spec:
  ports:
    - port: 6379
  selector:
    app: platform-redis
    tier: redis
  type: NodePort
#  clusterIP: None
