apiVersion: v1
kind: Service
metadata:
  name: app-tomcat
  labels:
    app: app-tomcat
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: app-tomcat
    tier: tomcat
