apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-app-mysql-pro
  labels:
    name: pv-app-mysql-pro
    environment: pro
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/pro/mysql-56"
