apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-mongo-pro
  labels:
    name: pv-mongo-pro
    environment: pro
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/pro/mongo"
