apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-nginx-config-pro
  labels:
    name: pv-nginx-config-pro
    environment: pro
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/pro/nginx"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-nginx-www-pro
  labels:
    name: pv-nginx-www-pro
    environment: pro
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/pro/nginx-www"
