apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-php-config-pro
  labels:
    name: pv-php-config-pro
    environment: pro
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.131
    path: "/data/pro/php"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-php-www-pro
  labels:
    name: pv-php-www-pro
    environment: pro
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.131
    path: "/data/pro/nginx-www"
