apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-platform-mysql-pro
  labels:
    name: pv-platform-mysql-pro
    environment: pro
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/pro/mysql-57"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-platform-mysql-config-pro
  labels:
    name: pv-platform-mysql-config-pro
    environment: pro
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/pro/mysql-57-config"
