apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-redis-pro
  labels:
    name: pv-redis-pro
    environment: pro
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.131
    path: "/data/pro/redis"
