apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-service-timer-pro
  labels:
    name: pv-service-timer-pro
    environment: pro
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.131
    path: "/data/pro/platform"
