apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-service-file-pro
  labels:
    name: pv-service-file-pro
    environment: pro
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/pro/platform"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-service-file-data-pro
  labels:
    name: pv-service-file-data-pro
    environment: pro
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/pro/static-file/platform"
