apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-tomcat-config-pro
  labels:
    name: pv-tomcat-config-pro
    environment: pro
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/pro/tomcat"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-tomcat-www-pro
  labels:
    name: pv-tomcat-www-pro
    environment: pro
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/pro/tomcat-www"
