apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-app-mysql-stg
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.91.210
    path: "/data/stg/mysql-56"
