apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-mongo-stg
  labels:
    name: pv-mongo-stg
    environment: stg
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/stg/mongo"
