apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-nginx-config-stg
  labels:
    name: pv-nginx-config-stg
    environment: stg
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/stg/nginx"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-nginx-www-stg
  labels:
    name: pv-nginx-www-stg
    environment: stg
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/stg/nginx-www"
