apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-redis-stg
  labels:
    name: pv-redis-stg
    environment: stg
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/stg/redis"
