apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-redis-stg
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.91.210
    path: "/data/stg/redis"
