apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-service-file-stg
  labels:
    name: pv-service-file-stg
    environment: stg
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.131
    path: "/data/stg/platform"
