apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-tomcat-config-stg
  labels:
    name: pv-tomcat-config-stg
    environment: stg
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/stg/tomcat"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-tomcat-www-stg
  labels:
    name: pv-tomcat-www-stg
    environment: stg
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.20.140
    path: "/data/stg/tomcat-www"
