apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-mysql-pv-claim
  namespace: tyfocg-pro
  labels:
    app: platform-mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: "pv-platform-mysql-pro"
    matchExpressions:
      - {key: environment, operator: In, values: [pro]}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-mysql-config-pv-claim
  namespace: tyfocg-pro
  labels:
    app: platform-mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      name: "pv-platform-mysql-config-pro"
    matchExpressions:
      - {key: environment, operator: In, values: [pro]}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: platform-mysql
  namespace: tyfocg-pro
  labels:
    app: platform-mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: platform-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7.18
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: platform-mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: platform-mysql-config-persistent-storage
          mountPath: /etc/mysql
        - name: localtime-config-volume
          mountPath: /etc/localtime
      volumes:
      - name: platform-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: platform-mysql-pv-claim
      - name: platform-mysql-config-persistent-storage
        persistentVolumeClaim:
          claimName: platform-mysql-config-pv-claim
      - name: localtime-config-volume
        hostPath:
          path: /etc/localtime
