apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-service-timer-pv-claim
  labels:
    app: platform-service-timer
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: platform-service-timer
  labels:
    app: platform-service-timer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: platform-service-timer
        tier: service-timer
    spec:
      containers:
      - image: pupudaye/centos-java
        command: [ "java","-jar","/data/service-timer/service-timer.war", "--spring.config.location=/data/service-timer/application.yml" ]
        name: platform-service-timer
        ports:
        - containerPort: 8096
          name: service-timer
        volumeMounts:
            - name: platform-service-timer-persistent-storage
              mountPath: /data
      volumes:
        - name: platform-service-timer-persistent-storage
          persistentVolumeClaim:
             claimName: platform-service-timer-pv-claim
